-- English translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'Login', 'Login');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TYPE', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDUCATIONAL_CONTEXT', 'Educational context');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UPDATED', 'Updated');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADDED', 'Added');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CREATED', 'Created');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPOSITORY_NUMBER', 'Repository number');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ALL_RIGHTS_RESERVED', 'All rights reserved');
insert into Translation(translationGroup, translationKey, translation) values (3, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DATA', 'Data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGE', 'Image');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXT', 'Text');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (3, 'APPLICATION', 'Application');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ASSESSEMENT', 'Assessment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BROADCAST', 'Broadcast');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CASESTUDY', 'Casestudy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COURSE', 'Course');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DEMONSTRATION', 'Demonstration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DRILLANDPRACTICE', 'Drill and practice');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDUCATIONALGAME', 'Educational game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ENQUIRYORIENTEDACTIVITY', 'Enquiry oriented game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPERIMENT', 'Experiment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPLORATION', 'Exploration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GLOSSARY', 'Glossary');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GUIDE', 'Guide');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LESSONPLAN', 'Lessonplan');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OPENACTIVITY', 'Open activity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESENTATION', 'Presentation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROJECT', 'Project');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCE', 'Reference');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ROLEPLAY', 'Roleplay');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SIMULATION', 'Simulation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXTBOOK', 'Textbook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOOL', 'Tool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBSITE', 'Website');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BOOKMARKSHARINGPLATFORM', 'Bookmark sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGESHARINGPLATFORM', 'Image sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCESHARINGPLATFORM', 'Reference sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SOUNDSHARINGPLATFORM', 'Sound sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEOSHARINGPLATFORM', 'Video sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBLOG', 'Weblog');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WIKI', 'Wiki');